# Generated by Django 6.0.2 on 2026-05-07 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('content_type', models.CharField(default='markdown', max_length=20, verbose_name='内容类型')),
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='core.mediaitem')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
                'ordering': ['-media_item__created_at'],
            },
        ),
    ]
