# Generated by Django 6.0.2 on 2026-05-07 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(max_length=32, unique=True, verbose_name='分享码')),
                ('password', models.CharField(blank=True, max_length=32, verbose_name='访问密码')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mediaitem', verbose_name='媒体项目')),
            ],
            options={
                'verbose_name': '分享',
                'verbose_name_plural': '分享',
                'ordering': ['-created_at'],
            },
        ),
    ]
