# Generated by Django 6.0.2 on 2026-05-07 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=255, verbose_name='艺术家')),
                ('album', models.CharField(blank=True, max_length=255, verbose_name='专辑')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='时长（秒）')),
                ('file', models.FileField(blank=True, null=True, upload_to='music/%Y/%m/', verbose_name='音乐文件')),
                ('external_url', models.URLField(blank=True, help_text='网易云/QQ音乐等外部链接', verbose_name='外部链接')),
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='core.mediaitem')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'ordering': ['-media_item__created_at'],
            },
        ),
    ]
